{% set name = "keras_mixed_sequence" %}
{% set version = "1.0.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/keras_mixed_sequence-{{ version }}.tar.gz
  sha256: d0f9af0279dddb6dfbf0f32430b0c5e71becbcb5d1f15d29be8e2296223f2e7f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - tqdm
    - numpy
    - tensorflow

test:
  imports:
    - keras_mixed_sequence
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LucaCappelletti94/keras_mixed_sequence
  summary: Lazily loading mixed sequences using Keras Sequence, focused on multi-task models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dillonroach
    - isuruf
